### ISSUE TITLE
what would be a good way to get a list of only "real" mount points?

### ISSUE THREAD

**Issue by FlorinAndrei** [djberg96/sys-filesystem#13]
If I do...

```
Filesystem.mounts{ |mount| p mount }
```

...then I get a huge list of mount points. Most of those are only useful to the system. But I'm solely interested in the volumes that can actually be used by a regular user to store files. Basically, the stuff in /etc/fstab except swap. I need to filter out everything else.

E.g., in this list, only / and /boot are volumes I'm interested in:

```
# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root  6.7G  2.9G  3.9G  44% /
devtmpfs                 913M     0  913M   0% /dev
tmpfs                    921M     0  921M   0% /dev/shm
tmpfs                    921M  8.4M  913M   1% /run
tmpfs                    921M     0  921M   0% /sys/fs/cgroup
/dev/sda1                497M  163M  335M  33% /boot
```

This is /etc/fstab on that machine, for comparison:

```
# cat /etc/fstab 
/dev/mapper/centos-root /                       xfs     defaults        1 1
UUID=4fe961ff-8508-4d2e-8997-947b6f2a57c4 /boot                   xfs     defaults        1 2
/dev/mapper/centos-swap swap                    swap    defaults        0 0
```

Is there a way to do the filtering directly with the library, or do I have to start hunting around the OS for that info?

Context:

I'm on Linux, and I'm trying to use this library as a lightweight way to get disk usage info. I am writing an extension for Sensu and I need to avoid spawning new processes to get disk usage info, otherwise I would just run "df". But the extension may trigger as often as once every few seconds, or even down to once ever 1 sec, so spawning is forbidden; all I can do is File.open() like stuff, read content, parse, print it out, file.close().

The extension must get a list of "real" volumes, determine the disk usage percentage for each, then return the list. I know how to do most of it, I'm just pondering the best way to eliminate non-user-related volumes.

**Comment by djberg96** [comment]
I don't remember the details, but couldn't you check the result of mount#mnt_type or mount#mnt_opts to indicate if it's the appropriate type?

**Comment by FlorinAndrei** [comment]
I looked at it.

If I filter by exclusion, I'm not sure the list is comprehensive enough - maybe there are other types that I should be excluding, that will pop up in the future.

If I filter by inclusion... hmmm... it might work, but again the list would have to be comprehensive enough.

If I could find somewhere a list of all possible types, I might be able to create the right filters.

**Comment by djberg96** [comment]
I think a bonafide sysadmin could probably help you more than I can with filtering that, since I'm not completely sure. Or perhaps a #linux irc channel.

**Comment by djberg96** [comment]
Alright, I'm going to modify the mounts method so that it calls statfs on each mount in turn, and that will provide you with more information that you can filter on.

**Comment by djberg96** [comment]
Need to get back to this at some point...

**Comment by djberg96** [comment]
On second thought, I think you're going to have to rely on `mnt_type` (probably ext4 or something similar) to get what you want. I'd rather not bloat the existing code, especially since I don't think the statfs information is going to be any more insightful.
