### ISSUE TITLE
Reported block_size on FreeBSD 10 is incorrect

### ISSUE THREAD

**Issue by mikeowens** [djberg96/sys-filesystem#14]
The block_size reported on FreeBSD is incorrect. The fragment_size seems to be the correct block size.  I found in the source a special case for OSX where the block_size is corrected by dividing by 256. This correction worked for the ZFS filesystem case (giving the correct block size), but not for UFS. I am not sure what the correct solution is here to get the right block size. But the correct way to compute the actual file system size in both cases is to not go by block size and use fragment size. For example, the size in GB for the root fs would be
```
stat = Filesystem.stat('/')
(stat.fragment_size * stat.blocks)/(1024*1024*1024)
```

**Comment by djberg96** [comment]
Ah, thanks. If that's the universal solution for both OSX and FreeBSD then please submit a patch and I'll merge it.

**Comment by mikeowens** [comment]
I am not sure if that is the solution for OSX as I don't have access to that. But for FreeBSD it seems to be. I will submit patch for that as soon as I have time.

**Comment by djberg96** [comment]
Was merged into last release. Thanks!

**Comment by djberg96** [comment]
Upon further review, I don't think the `block_size` was "wrong", just that it shouldn't be used in space calculations. Instead, we should use the `fragment_size` as you mentioned.
