### ISSUE TITLE
Getting a RuntimeError exception when requiring

### ISSUE THREAD

**Issue by xanview** [djberg96/sys-filesystem#17]
I installed this on Ruby 2.3.0 running on Alpine Linux. I am seeing the following, any ideas?

```
irb(main):001:0> require 'sys/filesystem'
RuntimeError: 
	from /usr/local/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:263:in `attach'
	from /usr/local/lib/ruby/gems/2.3.0/gems/ffi-1.9.10/lib/ffi/library.rb:263:in `attach_function'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem/functions.rb:13:in `<module:Functions>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem/functions.rb:5:in `<class:Filesystem>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem/functions.rb:4:in `<module:Sys>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem/functions.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem.rb:3:in `require_relative'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/unix/sys/filesystem.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/filesystem.rb:11:in `require_relative'
	from /usr/local/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.5/lib/sys/filesystem.rb:11:in `<top (required)>'
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/local/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):1
	from /usr/local/bin/irb:11:in `<main>'
```

**Comment by djberg96** [comment]
Looks like it's failing on:

    attach_function(:statvfs, [:string, :pointer], :int)

I'm not familiar with Alpine Linux. Is statvfs not exported by libc?

**Comment by xanview** [comment]
Not quite sure - I switched to Debian as I had other issues too.

**Comment by jmontleon** [comment]
FWIW on RHEL it was due to selinux; almost identical error.

**Comment by djberg96** [comment]
@jmontleon Thanks for the info. Not much I can do about it I'm afraid.

**Comment by jmontleon** [comment]
I agree - just wanted to leave a note in case anyone else found this doing a search as I did in order to potentially save them some frustration.

**Comment by jirutka** [comment]
> I'm not familiar with Alpine Linux. Is statvfs not exported by libc?

Alpine uses [musl libc](http://www.musl-libc.org/), but that’s not the problem, musl exports `statvfs`.

The problem is with [FFI](https://github.com/ffi/ffi) and [PaX](https://wiki.archlinux.org/index.php/PaX). One can disable PaX mprotect for `ruby` process (`paxctl -m /usr/bin/ruby`), but it’s a potential security hole.

**Comment by djberg96** [comment]
@jirutka I would recommend posting on the FFI project if that's something they can deal with.

**Comment by srse** [comment]
@jirutka thanks for posting this here! This just saved me a lot of time trying to figure out why ffi (attach/attach_function) in ruby would generate a RuntimeError on Gentoo. I would also recommend letting the ffi project/ ffi users know (@tduehr: pull request: https://github.com/ffi/ffi/pull/533)
