### ISSUE TITLE
is it semantically versioned?

### ISSUE THREAD

**Issue by matkoniecz** [djberg96/sys-filesystem#19]
During building my gem I encountered

```
WARNING:  pessimistic dependency on sys-filesystem (~> 1.1.4) may be overly strict
  if sys-filesystem is semantically versioned, use:
    add_runtime_dependency 'sys-filesystem', '~> 1.1', '>= 1.1.4'
```

In readme and in repository search I failed to find answer for this question.

**Comment by djberg96** [comment]
@matkoniecz I don't have a formal policy, but I think I've basically followed semver for all my projects, so "~> 1.1" should be fine.

**Comment by matkoniecz** [comment]
Thanks!
