### ISSUE TITLE
For windows, blocks_available should be the same as blocks_free instead of same as blocks

### ISSUE THREAD

**Issue by MaxLap** [djberg96/sys-filesystem#20]
On Unix, `blocks_available` is the unused blocks that are available to regular processes, so we can be sure that it's value is smaller or equal to `blocks_free`. (it's the value used by `df`)

On Windows, `blocks_available` returns the total number of blocks. This is not a good fallback to help cross compatibility. The command to check if you have available space to do something on Unix will, on Windows, say that the whole drive is yours.

**Comment by djberg96** [comment]
Looking back at this code, I think there are larger issues. I'll see if I can put together a PR soon.

**Comment by djberg96** [comment]
@MaxLap I think some poorly chosen variable names got me confused. Anyway, here's a proposed PR:

https://github.com/djberg96/sys-filesystem/compare/fix_windows_blocks?expand=1

If that looks right to you let me know and I'll merge it, and push out an updated gem.

**Comment by MaxLap** [comment]
Thank you for you help on this. On Monday i will be able to test the code on a Windows machine and ensure that everything makes sense before you do the merge. 

As for the PR, i noticed 2 things: 
* sectors_ptr and bytes_ptr are not freed. Maybe that is normal, I don't know much about ffi, put you freed the other 2 ptr variables you renamed. 
* the comment that goes with the blocks_available accessor still mentions it being the same as blocks.

As a side note, do you think adding cases in the tests to ensure blocks >= blocks_free >= blocks_available makes sense?

**Comment by djberg96** [comment]
@MaxLap I've updated the comments, added some sanity tests, and explicitly freed those pointers.

**Comment by djberg96** [comment]
@MaxLap sys-filesystem 1.1.7 released. Thanks for the report!
