### ISSUE TITLE
Filesystem.stat works with C:\, C:/, but fails with just C:

### ISSUE THREAD

**Issue by rubycoder** [djberg96/sys-filesystem#25]
Hi Dan,

I haven't made it to many RubyConfs lately, so I don't think I've talked with you since way back at Denver '06.

sys-filesystem is really useful.  Thanks for writing it!  I'm currently using it in a tiny program for a friend.  If I actually get paid for this, I'll send you something on Gratipay.

I've come across a little inconsistency.  I certainly wouldn't call it a 'bug', but I thought it was worth mentioning:

On both Win 7 Professional SP1 64-bit and Win 10 Pro 64-bit, if I call Filesystem.stat with either 'C:\\\\' or 'C:/', it works as expected.  But if I call it with 'C:', I get the error "The filename, directory name, or volume label syntax is incorrect."

This wouldn't seem too odd, except that on any other drive I've tried, calling it with 'D:', 'Q:' or whatever works fine. I've tested this with other partitions on the same hard drive as C:, other partitions on a different hard drive, and USB drives.

	$stdout.sync = true

	require 'sys/filesystem'
	include Sys

	Filesystem.mounts {|mount| p mount}

	p Filesystem.stat('Q:')       # other partition on same hard disk as C:
	p Filesystem.stat('D:')       # USB drive
	p Filesystem.stat('C:\\')
	p Filesystem.stat('C:')

#

	#<Sys::Filesystem::Mount:0x248cc70 @mount_point="C:\\", @mount_time=2017-04-30 18:45:32 -0700, @name="\\Device\\HarddiskVolume4", @mount_type="NTFS", @options="casepres,casesens,compression,namedstreams,pacls,encryption,objids,rpoints,sparse,unicode">
	#<Sys::Filesystem::Mount:0x248c550 @mount_point="D:\\", @mount_time=2017-04-30 18:45:32 -0700, @name="\\Device\\HarddiskVolume7", @mount_type="FAT32", @options="casepres,unicode">
	#<Sys::Filesystem::Mount:0x248c0d0 @mount_point="Q:\\", @mount_time=2017-04-30 18:45:32 -0700, @name="\\Device\\HarddiskVolume5", @mount_type="NTFS", @options="casepres,casesens,compression,namedstreams,pacls,encryption,objids,rpoints,sparse,unicode">
	#<Sys::Filesystem::Stat:0x2549f88 @path="Q:", @block_size=4096, @blocks=3671807, @blocks_available=668676, @blocks_free=668676, @name_max=255, @base_type="NTFS", @flags=65470719, @filesystem_id=1846093724, @bytes_free=2738896896>
	#<Sys::Filesystem::Stat:0x2549820 @path="D:", @block_size=16384, @blocks=3827889, @blocks_available=3161775, @blocks_free=3161775, @name_max=255, @base_type="FAT32", @flags=6, @filesystem_id=2139361986, @bytes_free=51802521600>
	#<Sys::Filesystem::Stat:0x24b8e78 @path="C:\\", @block_size=4096, @blocks=121297663, @blocks_available=16512052, @blocks_free=16512052, @name_max=255, @base_type="NTFS", @flags=65470719, @filesystem_id=874155169, @bytes_free=67633364992>
	C:/Ruby231p112/lib/ruby/gems/2.3.0/gems/sys-filesystem-1.1.7/lib/sys/windows/sys/filesystem.rb:318:in `stat': The filename, directory name, or volume label syntax is incorrect. - GetVolumInformation (SystemCallError)
		from C:/Users/wayne/test_project/lib/find_mount.rb:11:in `<top (required)>'
		from -e:1:in `load'
		from -e:1:in `<main>'

	Process finished with exit code 1
	
As I said, not a big deal.  The scenario that concerns me is that someone uses it without the / or \\\\, and only tests it on drives other than C:.  Then in production it happens to get called on C:

**Comment by djberg96** [comment]
Hi Wayne, long time no see.

Well, I do mention in the docs that you should include a trailing slash. This is actually a requirement by the `GetVolumeInformation` function:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa364993(v=vs.85).aspx

My *guess* is that this is an artifact of supporting drive-current paths. I *think* it will fail if you `cd C:\foo` and then try to `Filesystem.stat('D:')` if the drive-current directory for the "D" drive happens to be `D:\foo`, but I cannot test right now.

Anyway, this is basically undocumented behavior by MS. If it happens to work without the trailing slash then you've just been getting lucky.
