### ISSUE TITLE
Wrong FFI structs on Linux (and memory corruption on 32-bit ARM systems)

### ISSUE THREAD

**Issue by vihai** [djberg96/sys-filesystem#35]
Hello,

I'm not creating a pull request because I cannot test on various kernels and architectures so my patch may break other systems.

However, the FFI struct passed to statvfs is wrong and too short on 32-bit architectures, in facts it was corrupting memory and leading to a very nasty interpreter crash in random positions.

I tested the following struct with kernel 5.3.0 on x86-64 and with kernel 4.19.73 on armv7 and it seems to work. fsid may need to be changed to :ulong and properly aligned on big-endian architectures.

```
          layout(
            :f_bsize, :ulong,
            :f_frsize, :ulong,
            :f_blocks, :uint64,
            :f_bfree, :uint64,
            :f_bavail, :uint64,
            :f_files, :uint64,
            :f_ffree, :uint64,
            :f_favail, :uint64,
            :f_fsid, :uint64,
            :f_flag, :ulong,
            :f_namemax, :ulong,
            :f_spare, [ :ulong, 6 ],
          )
```

Thank you and keep up with the good work!

**Comment by djberg96** [comment]
Yeah, I'm not sure where I got that, maybe older versions of Linux? I can definitely see that `sizeof(struct statvfs)` is 112 on my Fedora VM, while the current code comes back with 128. Yours comes back with the correct 112.

Thanks for the report. I'll see if I can come up with a more robust way of setting this, but may just use your struct for now.

**Comment by djberg96** [comment]
Looking at this, I think Statfs is busted on Linux, too.

**Comment by djberg96** [comment]
@vihai Please take a look at https://github.com/djberg96/sys-filesystem/pull/36

**Comment by djberg96** [comment]
Well, I pushed out 1.3.1 this afternoon which addresses this issue. Enjoy!

**Comment by vihai** [comment]
Thank you, I confirm the latest release (1.3.1) is working fine on my systems!
