### ISSUE TITLE
Reported sizes are way off on Raspbian Linux (Buster)

### ISSUE THREAD

**Issue by smoyth** [djberg96/sys-filesystem#39]
Great gem! Thanks for making it!

Tried ext3 and ext4 partition types.

Gem is reporting:

```
irb(main):002:0> s = Sys::Filesystem.stat("/backup")
=> #<Sys::Filesystem::Stat:0x0200af30 @path="/backup", @block_size=4096, @fragment_size=4096, @blocks=16413548237976932, @blocks_free=4197385642661014, @blocks_available=4197338395371893, @files=1821269666, @files_free=1095216664576, @files_available=0, @filesystem_id=0, @flags=0, @name_max=0, @base_type=nil>
```

But the partition is only about 13.8GiB

Thoughts? Is this what is meant by "better 64bit support for Linux"?

**Comment by djberg96** [comment]
Based on what I'm reading online, I think this because you're using ext3/ext4, but I can't get a clear answer as to what the appropriate calculation is.

**Comment by djberg96** [comment]
Then again, maybe not. Does this patch work?

```
--- a/lib/sys/unix/sys/filesystem/functions.rb
+++ b/lib/sys/unix/sys/filesystem/functions.rb
@@ -7,7 +7,7 @@ module Sys
 
       ffi_lib FFI::Library::LIBC
 
-      if RbConfig::CONFIG['host_os'] =~ /sunos|solaris/i
+      if RbConfig::CONFIG['host_os'] =~ /sunos|solaris|linux/i
         attach_function(:statvfs, :statvfs64, [:string, :pointer], :int)
       else
         attach_function(:statvfs, [:string, :pointer], :int)
```

**Comment by smoyth** [comment]
I will take a look and let you know.

**Comment by smoyth** [comment]
Much better! It gets the total blocks bang on. The free blocks are a bit off, see:

```
deploy@field12:~/panel $ df
Filesystem     1K-blocks    Used Available Use% Mounted on
...
/dev/mmcblk0p3  15324520   41096  14485268   1% /backup

irb(main):002:0> s = Sys::Filesystem.stat("/backup")
=> #<Sys::Filesystem::Stat:0x01f66fb0 @path="/backup", @block_size=4096, @fragment_size=4096, @blocks=3831130, @blocks_free=3820856, @blocks_available=3621317, @files=977280, @files_free=977255, @files_available=977255, @filesystem_id=2266657906, @flags=0, @name_max=4096, @base_type=nil>
irb(main):003:0> s.blocks * 4
=> 15324520   <----------- Exactly right
irb(main):004:0> s.blocks_free * 4
=> 15283424   <----------- Too high, compared to `df`
```

Is this due to some filesystem thing I don't understand?

**Comment by smoyth** [comment]
Oh wait a sec, there is blocks available and blocks free... I guess I don't understand the difference. Will read up on that! Thanks! Could you release this patch when you are able please?

**Comment by djberg96** [comment]
@smoyth I'm trying to remember why I didn't default to statvfs64. I'm looking back at this:

https://github.com/djberg96/sys-filesystem/commit/41658cd87136bf4001575691f401c6bb2f24d1ff

https://github.com/djberg96/sys-filesystem/issues/5

I'm guessing there was some kind of struct mismatch on some of the platforms, but then later I updated the struct.

**Comment by djberg96** [comment]
Alright, pushed out 1.3.3. Closing.

**Comment by smoyth** [comment]
Thank you!!!
