### ISSUE TITLE
No such process - GetDiskFreeSpaceEx

### ISSUE THREAD

**Issue by Mcgeecorp** [djberg96/sys-filesystem#51]
I have run into this error on one of my Windows boxes with previously working code: "No such process - GetDiskFreeSpaceEx" 

The machine in question is Windows 10 64bit, as are the others that seem to work fine. I'm running Ruby 2.7.2 64bit with a current MSYS2 devkit. I've tried sys-filesystem 1.4.0 and 1.4.1.

Any suggestion as to what might be causing this?

**Comment by djberg96** [comment]
Can you provide a code snippet that demonstrates the problem? Which method are you calling? And on which file/directory?

**Comment by Mcgeecorp** [comment]
Nevermind - on the machine in question the code was trying to stat a non-existent directory.

Sorry for the noise!

**Comment by djberg96** [comment]
No worries. That's not the most helpful error message, though, I agree. Anyway, closing this one out.
