### ISSUE TITLE
Include ffi-stat?

### ISSUE THREAD

**Issue by lwoggardner** [djberg96/sys-filesystem#54]
Hi I am creating ruby ffi bindings for libfuse and will depend on this project for the statvfs structs.

I'm wondering if including the base stat struct would be a good fit here too. There is an ffi-stat project but it is unmaintained.

Happy to provide a PR if you think it fits here.

**Comment by djberg96** [comment]
Interesting, but would it provide some advantage for this library that I'm not seeing? I'm also not very keen on using an unmaintained library.

I would say if the stat wrapper itself is all you're after, then fork that project (assuming you can, I've never tried forking an archived project), and use your fork instead.

**Comment by lwoggardner** [comment]
I was thinking to fork it into this project, thus providing a unified view across the Unix filesystems for stat information.  

But if this project is strictly focused on filesysyems as a whole (rather than individual files) then yes I'll just take the stat structs into my project.

**Comment by djberg96** [comment]
Yes, this is really more about filesystems than files, so I think I will pass on it. Thanks for mentioning it, I was not aware of it previously.
